data:
  image_folder: "data/anime-faces"
  interpolation: "bicubic"
  image_size: 64

opt:
  gpus: 1
  batch_size: 128
  n_epochs: 1
  val_interval: 0.5
  accumulate_grad_batches: 1
  n_warmup_steps: 0.1

  lr: 0.0002
  w_decay: 0.01
  scheduler: cosine

  n_diffusion_steps: 100
  noise_range: [0.0001, 0.04]

seed: 57
offline_logging: True
